name: AVA
on: [push, pull_request]
jobs:
 check:
  runs-on: ${{ matrix.os }}
  strategy:
   matrix:
    os: [ubuntu-latest, macos-latest, windows-latest]
  steps:
   - uses: actions/checkout@v2
   - name: Setup Node
     uses: actions/setup-node@v1
     with:
      node-version: '12.x'
   - name: Install dependencies
     run: yarn
   - name: Test
     run: yarn test
